### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so

### ISSUE THREAD

**Issue by tiadams** [BuffaloDan/FractalRenderer#1]
Wollte das eben mal ausprobieren, läuft das auf Linux? :D

**Comment by BuffaloDan** [comment]
https://github.com/BuffaloDan/FractalRenderer/commit/080e35f99bf59e2657ecbcae994b7e343a388b42 sollte das Problem behoben haben :D
Hier ne fertige Distribution: [FractalRenderer](https://ci.buffalodan.de/job/FractalRenderer/lastBuild/)
Konnte das leider nicht testen, VMs mögen OpenCL wohl nicht

**Comment by tiadams** [comment]
packst du die main class ins manifest?

bauen klappt, wenn ich FractalRenderer/app/build/scripts/app ausführe bekomme ich:

`Error: Could not find or load main class de.buffalodan.fractal.app.DesktopApp`
